export const financeCategories = [
  "Fixed contribution",
  "Meal package",
  "Guest meals",
  "Donation",
  "Catering",
  "Decoration",
  "Mandap",
  "Puja & prasad",
  "Music & sound",
  "Events",
  "Utilities",
  "Transport",
  "Supplies",
  "Reimbursement",
  "Transfer",
  "Opening funds",
  "Refund",
  "Other",
] as const;
